services:
  nginx:
    image: nginx:alpine
    ports:
      - "8080:8080"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./frontend:/usr/share/nginx/html
    networks:
      - frontend-network
    depends_on:
      backend:
        condition: service_healthy
    restart: unless-stopped

  backend:
    build: ./backend
    env_file:
      - .env.backend
      - .env.db
    networks:
      - backend-network
      - frontend-network
    privileged: true
    volumes:
      - ./backend/uploaded_files:/app/uploaded_files
      - code_runner_data:/var/lib/docker
    depends_on:
      db:
        condition: service_healthy
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:8000/health || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 10

  db:
    image: mysql:8.0
    env_file: .env.db
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - backend-network
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 5s
      timeout: 2s
      retries: 10

  pma:
    image: phpmyadmin/phpmyadmin
    environment:
      PMA_HOST: db
      PMA_PORT: 3306
      UPLOAD_LIMIT: 100M
    networks:
      - backend-network
      - frontend-network
    depends_on:
      - db
    restart: unless-stopped


volumes:
  db_data:
  code_runner_data:


networks:
  frontend-network:
    driver: bridge
  backend-network:
    driver: bridge
